spring.application.name=imoveis
spring.datasource.url=jdbc:postgresql://localhost:5432/sigai_imoveis
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true